version: 0.0
os: linux
files:
  - source: /web_server.py
    destination: /opt/ads-server/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root



